#!/bin/bash

. ./environ.sh

$ANACONDA_BUILDINSTALL --debug --version $VERSION --brand $PRODUCT_NAME --product $PRODUCT_NAME --release $RELEASE --final --output $OVIRT_ALLINONE_BASE/$ISO_DATA_PATH $OVIRT_ALLINONE_BASE/$ISO_DATA_PATH $LOCAL_REPO1 $LOCAL_REPO2 $LOCAL_REPO3 $LOCAL_REPO4 $LOCAL_REPO5
